version: '2'

services:
  fuel_app:
    container_name: fuel_app
    build: app
    image: fuelphpdocker/app
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./app/fuel_app:/var/www/app"
    ports:
      - "80:80"
    links:
      - "fuel_db:fuel_db"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_HOSTNAME: fuel_db

  fuel_db-data:
    container_name: fuel_db-data
    image: busybox:latest
    volumes:
      - /var/lib/mysql

  fuel_db:
    container_name: fuel_db
    build: db
    image: fuelphpdocker/db
    depends_on:
      - "fuel_db-data"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    volumes_from:
      - fuel_db-data
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
